export const HELP_OPTIONS: string[] = [
  // Technology & Software
  "cameraman",
  "camera operator",
  "broadcast technician",
  "broadcast engineer",
  "teleprompter operator",
  "boom operator",
  "gaffer",
  "key grip",
  "best boy",
  "location scout",
  "production assistant",
  "script supervisor",
  "stunt coordinator",
  "stunt performer",
  "special effects coordinator",
  "prop master",
  "set decorator",
  "location manager",
  "production coordinator",
  "talent coordinator",
  "Accountant",
  "Accountant (Articleship)",
  "Accountant (Part -Time)",
  "Accounts Admin",
  "Accounts Assistant",
  "Accounts Associate",
  "Accounts Executive",
  "Accounts Head",
  "Accounts Manager",
  "Audit / Account Assistant",
  "Audit Executive",
  "Audit Manager",
  "Auditor",
  "Chartered Accountant",
  "Company Secretary",
  "Cost Accountant",
  "Credit Analyst",
  "Credit Controller",
  "Finance / Accounts",
  "Finance Executive",
  "Financial Accountant",
  "Junior Accountant",
  "Senior Accountant",
  "Tally Operator",
  "Tax Assistant",
  "2D/3D Architect",
  "2D/3D Interior Designer",
  "Architect",
  "Assistant Architect",
  "AutoCAD Designer",
  "Diploma/Degree Architect",
  "Draftsman Architect",
  "Draughtsman Architect",
  "Furniture Designer",
  "Interior Designer",
  "Interior Draftsman",
  "Interior Site Supervisor",
  "Junior Architect",
  "Modular Kitchen Designer",
  "Senior Architect",
  "Admin Executive - Back Office",
  "Administrative Assistant",
  "Assistant Operations Manager",
  "Associate Hotel Manager",
  "Back Office Coordinator",
  "Back Office Executive",
  "Back Office Marketing Executive",
  "Back Office Operations",
  "Back Office Sales Assistant",
  "Back Office Staff",
  "Banking Assistant",
  "Business Development Executive - Back Office",
  "Business Development Manager - Back Office",
  "Business Operations Manager",
  "CSR Manager",
  "Cafe Manager",
  "Clerk",
  "Computer Operator",
  "Computer Typist - Back Office",
  "Dairy Farm Manager",
  "Data Entry Operator",
  "Data Operator",
  "Delivery Manager",
  "Document Scanning (Office)",
  "Document Verification (Office)",
  "Ecommerce Operations Executive",
  "Executive Assistant - Back Office",
  "Executive Secretary",
  "Factory Manager",
  "Fleet Manager",
  "Food and Beverage Manager",
  "Helpdesk Executive (Office)",
  "Hospitality Manager",
  "Hospitality Trainer",
  "Hotel Manager",
  "Hotel Sales Manager",
  "Housekeeping Manager",
  "Housekeeping Officer",
  "Housekeeping Team Leader",
  "Import Export Executive",
  "Inventory Manager",
  "Junior Clerk",
  "Logistics Manager",
  "Lower Division Clerk (LDC)",
  "MIS Executive",
  "Mall Manager",
  "Office Admin",
  "Office Assistant - Back Office",
  "Office Coordinator",
  "Office Executive - Back Office",
  "Operation Executive",
  "Operation Manager",
  "Operations Associate",
  "Petrol Pump Manager",
  "Purchase Executive",
  "Purchase Manager",
  "Quality Control Manager",
  "Restaurant Manager",
  "Secretary",
  "Senior Clerk",
  "Senior Delivery Manager",
  "Senior Hotel Manager",
  "Service Advisor/ Incharge",
  "Society Manager",
  "Stock Manager",
  "Supervisor",
  "Survey Clerk",
  "System Admin - Back Office",
  "Warehouse Executive",
  "Warehouse Manager",
  "Beautician",
  "Beauty Advisor",
  "Beauty Consultant",
  "Beauty Director",
  "Beauty Therapist",
  "Body Massage Therapist",
  "Hair Cutting Executive",
  "Hairdresser",
  "Junior Beautician",
  "Laser Hair Removal Technician",
  "Mehandi Artist",
  "Nail Art Technician",
  "Salon Worker",
  "Senior Beautician",
  "Skin Cosmetic Treatment Assistant",
  "Spa Therapist",
  "Stylist",
  "Unisex Hairdresser",
  "Business Analyst",
  "Business Developer",
  "Business Development Executive",
  "Business Development Executive",
  "Business Development Manager",
  "Business Development Officer",
  "Business Initiatives Executive",
  "Business Initiatives Manager",
  "Business Intelligence Manager",
  "Business Manager",
  "Client Relationship Manager - Business Development",
  "Customer Relationship Executive - Business Development",
  "Customer Relationship Manager - Business Development",
  "Ecommerce Account Manager",
  "Online Sales Executive - Business Development",
  "Relationship Manager",
  "Relationship Officer - Business Development",
  "Sales Executive - Business Development",
  "Chemist",
  "Chemist - Production",
  "Chemist - Quality Control",
  "Junior Chemist",
  "Lab Chemist",
  "Pharmaceutical Chemist",
  "Senior Chemist",
  "Academic Content Writer",
  "Content Analyst",
  "Content Developer",
  "Content Editor",
  "Content Manager",
  "Content Marketing / Writing",
  "Content Writer",
  "Content Writer & Editor",
  "Editorial Assistant",
  "Senior Content Developer",
  "Senior Content Editor",
  "Senior Content Manager",
  "Assistant Cook",
  "Bakery Chef",
  "Barista",
  "Chef",
  "Chief Cook",
  "Chinese Cook",
  "Continental Cook",
  "Cook",
  "Fast Food Cook Job",
  "Head Cook",
  "Indian Cook",
  "North Indian Cook",
  "Pastry Cook",
  "Pizza Maker",
  "Senior Cook",
  "South Indian Cook",
  "Tandoor Cook",
  "Academic Counsellor",
  "Admission Counsellor",
  "Career Counsellor",
  "Counsellor",
  "Education Counsellor",
  "Investment Counsellor",
  "School Counsellor",
  "Senior Counsellor",
  "Travel Counsellor",
  "Cash Collection",
  "Collection",
  "Courier Delivery",
  "Delivery Boy",
  "Delivery Executive",
  "Delivery Head",
  "Document Collection",
  "Food Delivery",
  "Helper - Delivery",
  "Item Delivery",
  "Milk Delivery",
  "Payment Collection",
  "Pickup Boy",
  "Auto Driver",
  "Bus Driver",
  "Cab Driver",
  "Car Driver",
  "Company Driver",
  "Driver",
  "Heavy Driver",
  "Light Driver",
  "Ola / Uber Driver",
  "Personal Driver",
  "Private Company Driver",
  "Tempo Driver",
  "Truck Driver",
  "Vehicle Driver",
  "DTP Computer Operator",
  "DTP Designer",
  "DTP Executive",
  "DTP Operator",
  "DTP Promoter",
  "Junior DTP Operator",
  "Senior DTP Operator",
  "Assistant Production Manager",
  "Automobile Engineer",
  "Chemical Engineer",
  "Civil Design Engineer",
  "Civil Engineer",
  "Civil Site Engineer",
  "Civil Site Supervisor",
  "Construction Site Supervisor",
  "Diploma Civil Engineer",
  "Diploma Electrical Engineer",
  "Diploma Electronic Engineer",
  "Diploma Mechanical Engineer",
  "Electrical Design Engineer",
  "Electrical Engineer",
  "Electrical Maintenance Engineer",
  "Electronic Engineer",
  "Electronic Service Engineer",
  "Engineer",
  "Engineer Maintenance",
  "Engineering Draftsman",
  "Engineering Manager",
  "Fullfilment Centre Supervisor",
  "Logistics Supervisor",
  "Manufacturing Site Supervisor",
  "Mechanical Design Engineer",
  "Mechanical Engineer",
  "Mechanical Site Engineer",
  "Production Manager",
  "Project Engineer",
  "Quality Control Engineer",
  "Telecom Engineer",
  "Testing Engineer",
  "Warehouse Incharge",
  "Warehouse Supervisor",
  "Catering Assistant",
  "Event Assistant",
  "Event Coordinator",
  "Event Designer",
  "Event Manager",
  "Event Organizer",
  "Event Promoter",
  "Wedding Assistant",
  "Clothing Designer",
  "Dress Designer",
  "Fashion Consultant",
  "Fashion Design Faculty",
  "Fashion Designer",
  "Fashion Illustrator",
  "Fashion Marketer",
  "Fashion Merchandiser",
  "Garment Designer",
  "Jewellery Designer",
  "Kurti Designer",
  "Saree/Blouse Designer",
  "Shoe Designer",
  "Textile Designer",
  "Area Sales Manager",
  "Area Sales Officer",
  "Assistant Sales Manager",
  "Brand Promoter - Field Sales",
  "Channel Sales Executive (Software)",
  "Client Relationship Manager - Field Sales",
  "Corporate Product Sales",
  "Corporate Sales Executive",
  "Corporate Tie Ups",
  "Credit Card Sales",
  "Customer Relationship Executive - Field Sales",
  "Customer Relationship Manager - Field Sales",
  "Customer Sales Executive",
  "Customer Verification Job",
  "Ecommerce Sales Executive",
  "FMCG Sales",
  "Field Collection Executive",
  "Field Sales & Marketing Executive",
  "Field Sales Coordinator",
  "Field Sales Executive",
  "Field Sales Manager",
  "Field Sales Officer",
  "Field Sales Representative",
  "IT Sales Executive",
  "Inspection Field Executive",
  "Insurance Advisor",
  "Insurance Sales",
  "KYC Field Executive",
  "Loan Sales",
  "Marketing Team Leader - Field Sales",
  "Medical Representative - Field Sales",
  "Medical Representative Sales",
  "Medical Sales",
  "Mutual Fund Sales",
  "Outbound Sales Executive",
  "Outside Sales Executive",
  "Product Marketing - Field Sales",
  "Promoter",
  "Promoter",
  "Promotion Sales",
  "Quality Survey Field Executive",
  "Real Estate Sales",
  "Relationship Officer",
  "SIM Card Sales",
  "Sales Coordinator / Executive",
  "Sales Executive - Field Sales",
  "Sales Manager",
  "Sales Representative",
  "Senior Field Sales Executive",
  "Senior Field Sales Manager",
  "Senior Field Sales Officer",
  "Senior Field Sales Representative",
  "Technical Sales Executive",
  "Tour Package Sales Executive - Field Sales",
  "2D Animator",
  "3D Animator",
  "3D Graphic Designer",
  "3D Modeling Designer",
  "Album Designer",
  "Animator",
  "Associate Graphic Designer",
  "Computer Designer (Printing Press)",
  "Corel Draw Designer",
  "Flash Animator",
  "Graphic Designer",
  "Multimedia Designer",
  "Photo Editor",
  "Photoshop Designer",
  "Photoshop specialist",
  "Senior Graphic Designer",
  "UI/UX Designer",
  "Video Editor",
  "Visual Effects (VFX) Designer",
  "Web & Graphic Designer",
  "Wedding Album Designer",
  "Associate Hardware Engineer",
  "Computer Hardware Engineer",
  "Desktop Support Engineer",
  "Hardware Engineer",
  "IT Hardware Engineer",
  "Mobile Hardware Engineer",
  "Network Engineer",
  "System Admin - Hardware Engineer",
  "Hospitality Assistant",
  "Hospitality Executive",
  "Host / Hostess Job",
  "Hotel Receptionist - Hospitality",
  "Laundry Helper",
  "Tour Package Sales Executive - Hospitality",
  "Bar Tender",
  "Cafe Staff",
  "Dish Washer",
  "Fast Food Helper",
  "Hotel Cleaner",
  "Hotel Receptionist - Hotel",
  "Kitchen Helper",
  "Kitchen Staff",
  "Restaurant Captain",
  "Restaurant Waiter",
  "Steward",
  "Waiter",
  "Waiter/Steward",
  "Cleaner",
  "Cleaning staff",
  "Helper - Housekeeping",
  "Housekeeping Associate",
  "Housekeeping Attendant",
  "Housekeeping Executive",
  "Housekeeping Helper",
  "Housekeeping Room Attendant",
  "Housekeeping Staff",
  "Housekeeping Supervisor",
  "HR Analyst",
  "HR Assistant",
  "HR Executive",
  "HR Head",
  "HR Manager",
  "HR Officer",
  "HR Recruiter",
  "Hr/Admin",
  "Human Resource Executive",
  "Human Resource Generalist",
  "IT Recruiter",
  "Recruiter",
  "Recruitment Associate",
  "Senior HR Executive",
  "Talent Manager",
  "US IT Recruiter",
  "Blood Collection Job",
  "Clinic Assistant",
  "Clinic Helper",
  "Dialysis Technician",
  "Endoscopy Technician",
  "Lab Assistant",
  "Lab Chemist / Technician",
  "Lab Technician",
  "Medical Lab Technician",
  "Pathology Lab Technician",
  "Phlebotomist",
  "Senior Lab Technician",
  "X Ray Technician",
  "Agriculture Helper",
  "Agriculture Worker",
  "Butcher",
  "Factory Helper",
  "Farm Helper",
  "Foreman",
  "Gardener",
  "Laborer",
  "Labour Officer",
  "Labour Supervisor",
  "Labourer",
  "Loader",
  "Mason Helper",
  "Poultry Farm Worker",
  "Press Man",
  "Advocate",
  "Associate Advocate",
  "Associate Lawyer",
  "Corporate Lawyer",
  "In House Advocate",
  "Junior Advocate",
  "Junior Lawyer",
  "Law Officer",
  "Lawyer",
  "Legal Advisor",
  "Legal Assistant",
  "Legal Associate",
  "Legal Consultant",
  "Legal Executive",
  "Legal Head",
  "Legal Manager",
  "Legal Officer",
  "Para Legal",
  "Public Prosecutor",
  "CNC Lathe Machine Operator",
  "CNC Machine Operator",
  "Heavy Machine Operator",
  "Junior Machine Operator",
  "Lathe Machine Operator",
  "Light Machine Operator",
  "Machine Maintenance Officer",
  "Machine Maintenance Supervisor",
  "Machine Operator",
  "Machine Supervisor",
  "Senior Machine Operator",
  "VMC Operator",
  "Baby Care",
  "Baby Sitter",
  "Domestic Helper",
  "House Maid",
  "House cleaner",
  "Household Helper",
  "Maid Job",
  "Nanny",
  "Brand Promoter - Marketing",
  "Content Marketing - Marketing",
  "Copywriter - Marketing",
  "Franchise Manager",
  "Marketing Executive",
  "Marketing Field Executive",
  "Marketing Head",
  "Marketing Manager",
  "Network Marketing",
  "Product Marketing",
  "Sales & Marketing Executive",
  "Sales Executive - Marketing",
  "Assistant Doctor",
  "Audiologist",
  "Ayurvedic Doctor",
  "Clinic Assistant Veterinary",
  "Clinic Treatment Assistant",
  "Dental Assistant",
  "Dental Assistant/Receptionist",
  "Dental Chairside Assistant",
  "Dental Hygienist",
  "Dentist",
  "Doctor",
  "General Physician",
  "Healthcare Assistant",
  "Homoeopathy Doctor",
  "Hospital Assistant",
  "Junior Doctor",
  "Medical Executive",
  "Medical Officer",
  "Medical Representative",
  "Medical Staff",
  "Medical Transcriptionist",
  "Optometrist",
  "Paediatric",
  "Para Vet",
  "Pathologist",
  "Pharmacist",
  "Physiotherapist Doctor",
  "Senior Doctor",
  "Vet Assistant",
  "Veterinary Doctor",
  "Home Care Nursing",
  "Nursing Superintendent",
  "Nursing Supervisor",
  "Patient Care - Nurse",
  "Staff Nurse",
  "Boutique Helper",
  "Garment Shop Helper",
  "Helper - Office Boy / Peon",
  "Helper / Peon",
  "Jewellery Shop Helper",
  "Kirana Helper",
  "Office Assistant - Office Boy / Peon",
  "Office Boy",
  "Office Boy (Full Time)",
  "Office Boy (Part Time)",
  "Office Boy / Helper",
  "Office Compounder",
  "Office Executive - Office Boy/Peon",
  "Office Girl",
  "Office Staff",
  "Office Worker",
  "Operations Assistant",
  "Packaging Boy",
  "Packing Helper",
  "Petrol Bunk Filling Boy",
  "Petrol Pump Filling Boy",
  "Photocopy Machine Operator",
  "Photostat Machine Operator",
  "Shop Boy/Helper",
  "Shop Helper",
  "Xerox Machine Operator",
  "Brand Promoter",
  "Copywriter - Online Marketing",
  "Creative Manager",
  "Digital Marketing Assistant",
  "Digital Marketing Executive",
  "E-commerce Marketing Executive",
  "Online Advertising",
  "Online Brand Promoting",
  "Online Community Manager",
  "Online Content Marketing",
  "Online Marketing Executive",
  "Online Marketing Executive",
  "Online Marketing Head",
  "Online Marketing Manager",
  "Online Marketing Strategist",
  "Online Media",
  "Online Product Marketing",
  "Online Retail",
  "Online Sales Executive",
  "SEO Executive",
  "Sales & Online Marketing Executive",
  "Social Media Manager",
  "Social Media Marketing",
  "Cinematographer",
  "Event Photographer",
  "Fashion Photographer",
  "Film Production Manager",
  "Freelance Photographer",
  "News Cameraman",
  "Photo Studio Assistant",
  "Photo Studio Cameraman",
  "Photographer",
  "Photographer & Videographer",
  "Product Photographer",
  "Videographer",
  "Wedding Photographer",
  "Wildlife Photographer",
  ".Net Developer",
  "Android Developer",
  "Angular Developer",
  "Asp.net Developer",
  "Backend Developer",
  "Cyber Security Consultant",
  "Dot Net Developer",
  "ERP Functional Consultant",
  "Front end Developer",
  "Full Stack Developer",
  "Hybrid App Developer",
  "IOS Developer",
  "IT Professional",
  "Information Security Analyst",
  "Information Security Consultant",
  "Java Developer",
  "Oracle Cloud Consultant",
  "PHP Developer",
  "Program Manager",
  "Programmer",
  "Programmer Analyst",
  "Python Developer",
  "SAP ABAP Consultant",
  "SAP Consultant",
  "SAP Trainer",
  "SAS Programmer",
  "SEO Developer",
  "SQL Developer",
  "Senior Programmer",
  "Software Developer",
  "Software Tester",
  "Technical / Functional Consultant",
  "Technology Analyst",
  "Web Designer",
  "Web Developer",
  "Wordpress Developer",
  "Admin Executive - Receptionist",
  "Executive Assistant - Receptionist",
  "Front Desk Executive",
  "Front Desk Receptionist",
  "Front Office Manager",
  "Front Office Receptionist",
  "Front Office/Sales Executive",
  "Hotel Receptionist",
  "Receptionist",
  "Receptionist/Sales Executive",
  "Apparel Sales Retail",
  "Assistant Store Incharge",
  "Boutique Helper - Retail",
  "Car Sales Executive",
  "Car Sales Retail",
  "Cashier",
  "Clothes Sales Retail",
  "Counter Sales",
  "Counter Sales Executive",
  "Counter Sales Guy",
  "Counter Salesman",
  "Electronics Sales Retail",
  "Eye Wear Sales Retail",
  "Food Chain Sales Retail",
  "Footwear Sales Retail",
  "Furniture Salesman",
  "Garment Salesman",
  "Garment Shop Helper - Retail",
  "Holiday Consultant",
  "Home Appliances Sales Retail",
  "Immigration Consultant",
  "Interior Showroom Sales Executive",
  "Jewellery Salesman",
  "Jewellery Shop Helper - Retail",
  "Mall Sales Executive",
  "Mobile Salesman",
  "Pharmacist Assistant",
  "Pharmacy Counter Salesman",
  "Retail Executive",
  "Retail Sales Executive",
  "Retail Sales Manager",
  "Retail Sales Officer",
  "Retailer",
  "Rice Salesman",
  "Sales Co-ordinator",
  "Sales Staff (In Shop)",
  "Saree Salesman",
  "Shop Assistant",
  "Shop Helper - Retail",
  "Shop Salesman",
  "Showroom Sales",
  "Showroom Sales Executive",
  "Sports Salesman",
  "Store Assistant",
  "Store Incharge",
  "Store Keeper",
  "Store Manager",
  "Store Officer",
  "Store Sales Executive",
  "Store Supervisor",
  "Sweet Salesman",
  "Textile Salesman",
  "Tour Package Sales Executive - Retail",
  "Travel Consultant",
  "Travel Sales Executive",
  "Warehouse Assistant",
  "Wholesale Salesman",
  "Bouncer",
  "House Watchman",
  "Security Guard",
  "Security Guard (Night Shift)",
  "Security Guard (Part Time)",
  "Security Guard Supervisor",
  "Security Officer",
  "Security Personnel",
  "Security Staff",
  "Watchman",
  "Boutique Tailor",
  "Cutting Master",
  "Designer Tailor",
  "Gents Tailor",
  "Industrial Tailor",
  "Ladies Tailor",
  "Leather Tailor",
  "Stitching Job",
  "Tailor Master",
  "Art & Craft Teacher",
  "Assistant Professor",
  "Assistant Teacher",
  "Biology Teacher",
  "Chemistry Teacher",
  "Coach",
  "College Teacher",
  "Commerce Teacher",
  "Computer Teacher",
  "Dance Teacher",
  "Economics Teacher",
  "English Teacher",
  "Head Master",
  "Head Mistress",
  "Hindi Teacher",
  "Hobby Teacher",
  "IELTS Teacher",
  "Kannada Teacher",
  "Language Teacher",
  "Librarian",
  "Library Assistant",
  "Marathi Teacher",
  "Maths Teacher",
  "Music Teacher",
  "Nursery Teacher",
  "PT Teacher",
  "Physical Education Teacher",
  "Physics Teacher",
  "Pre-Primary Teacher",
  "Preschool Teacher",
  "Primary Teacher",
  "Principal",
  "Professor",
  "SST Teacher",
  "School Teacher",
  "Science Teacher",
  "Secondary Teacher",
  "Sports Teacher",
  "Teacher",
  "Tuition teacher",
  "Tutor",
  "AC Mechanic",
  "AC Technician",
  "AC-HCAV Technician",
  "Aquaguard Technician",
  "Assembly Fitter",
  "Assistant Technician",
  "Automobile Fitter",
  "CCTV Technician",
  "Cable Technician",
  "Carpenter",
  "Computer Hardware Technician",
  "DTH Technician",
  "Draughtsman",
  "Electric Panel Designer",
  "Electrical Designer",
  "Electrician",
  "Electrician Helper",
  "Electronic Service Technician",
  "Elevator Technician",
  "Fabricator Fitter",
  "Fire Fighting Equipment",
  "Fire Technician",
  "Fire and Safety Operator",
  "Fitter",
  "Fitter Mechanic",
  "Fitter/Helper",
  "Fitter/Welder",
  "Fridge Mechanic",
  "Fridge Technician",
  "Furniture Fitter",
  "Gas Mechanic",
  "General Technician",
  "Glass Fitter",
  "Home Appliances Technician",
  "IT Technician/Network Technician",
  "ITI Electrician",
  "ITI Fitter",
  "ITI Technician",
  "Internet Technician",
  "Inverter Mechanic",
  "Kitchen Equipment Technician",
  "LED Designer",
  "LED Smart TV Technician",
  "Laptop Repair Technician",
  "Mechanic Motor Vehicle",
  "Mobile Technician",
  "Modular Kitchen Fitter",
  "PCB Designer",
  "Painter Job",
  "Pest Control Technician",
  "Plumber",
  "Plumber Fitter",
  "RO Technician",
  "Radio Technician",
  "Repair Technician",
  "Safety Officer",
  "Smart Phone technician",
  "Sound and Light Technician",
  "TV Technician",
  "Technical Assistant",
  "Technical Executive",
  "Tower Installation Technician",
  "Turner/Fitter",
  "Watch Mechanic",
  "Water Purifier Technician",
  "Water Treatment Technician",
  "Welder",
  "Wireman",
  "BPO Executive",
  "BPO Staff",
  "BPO Tele calling",
  "Call Center Executive",
  "Client Relationship Manager - Telecalling",
  "Customer Care Executive",
  "Customer Care Manager",
  "Customer Relationship Executive - Telecalling",
  "Customer Relationship Manager - Telecalling",
  "Customer Support Executive",
  "Indoor Sales Executive",
  "Inside Sales Executive",
  "International Call Center",
  "Relationship Officer - Telecalling",
  "Sales Executive - Telecalling ",
  "TeleMarketing",
  "Telecaller",
  "Telecaller Inbound",
  "Telecaller Outbound",
  "Telecalling",
  "Telecalling Assistant",
  "Telecalling Executive",
  "Telecalling Manager",
  "Telecalling Supervisor",
  "Telecalling Team Leader",
  "Telephone Operator",
  "Telesales",
  "Telesales Executive",
  "Tour Package Sales Executive - Telecalling",
  "Voice Process Associate",
  "Aptitude Trainer",
  "Corporate Trainer",
  "Dance Trainer",
  "Fitness Trainer",
  "Gym Trainer",
  "Junior Trainer",
  "Nutritionist",
  "Senior Trainer",
  "Soft Skills Trainer",
  "Trainer",
  "Voice & Accent Trainer",
  "Yoga Trainer",
  "Computer Typist",
  "Data Entry Operator - Back Office",
  "Stenographer",
  "Typist",
  "Typist & Clerk",
  "2 Wheeler Mechanic",
  "2 Wheeler Washer",
  "4 Wheeler Mechanic",
  "4 Wheeler Washer",
  "Auto Mechanic",
  "Auto Service Consultant",
  "Automobile Mechanic",
  "Bicycle Mechanic",
  "Bike Mechanic",
  "Car Alignment Technician",
  "Car Cleaner",
  "Car Detailer",
  "Car Dry Cleaner",
  "Car Mechanic",
  "Car Painter",
  "Car Polisher",
  "Car Technician",
  "Car Washer",
  "Motorcycle Mechanic",
  "Truck Mechanic",
  "Two Wheeler Technician",
  "Tyre Mechanic",
  "Hospital Ward Boy",
  "Patient Care - Ward Boy",
  "Ward Boy",
  "Ward Secretary",

  // Food & Dairy Industry
  "dairy farmer",
  "milk processor",
  "cheese maker",
  "dairy production manager",
  "dairy quality control specialist",
  "dairy plant operator",
  "milk delivery person",
  "dairy products distributor",
  "dairy farm manager",
  "dairy nutritionist",
  "ice cream maker",
  "dairy equipment technician",
  "dairy products tester",
  "dairy compliance officer",

  // Retail & Sales
  "retail salesperson",
  "cashier",
  "store manager",
  "retail merchandiser",
  "visual merchandiser",
  "inventory manager",
  "retail buyer",
  "sales associate",
  "shop owner",
  "boutique manager",
  "retail district manager",
  "retail operations manager",
  "loss prevention specialist",
  "retail trainer",

  // Maintenance & Repair
  "maintenance technician",
  "building superintendent",
  "handyman",
  "repair technician",
  "equipment maintenance specialist",
  "facilities maintenance worker",
  "maintenance supervisor",
  "industrial maintenance mechanic",
  "maintenance electrician",
  "building maintenance engineer",
  "property maintenance manager",

  // Textile & Garment Industry
  "textile worker",
  "garment worker",
  "textile machine operator",
  "fabric inspector",
  "textile designer",
  "garment pattern maker",
  "textile quality controller",
  "textile plant manager",
  "garment factory supervisor",
  "textile researcher",
  "fabric dyer",
  "textile printer",

  // Cleaning & Sanitation
  "cleaner",
  "sanitation worker",
  "cleaning supervisor",
  "industrial cleaner",
  "cleaning service manager",
  "sterilization technician",
  "cleaning company owner",
  "commercial cleaner",
  "residential cleaner",
  "crime scene cleaner",
  "biohazard cleaning specialist",

  // Waste Management
  "garbage collector",
  "recycling worker",
  "waste management operator",
  "waste treatment plant operator",
  "hazardous waste specialist",
  "waste collection driver",
  "waste facility manager",
  "composting specialist",
  "waste reduction coordinator",

  // Security & Protection
  "security guard",
  "bodyguard",
  "security supervisor",
  "security systems installer",
  "security consultant",
  "private investigator",
  "surveillance specialist",
  "security trainer",
  "security systems manager",
  "personal protection officer",
  "event security coordinator",

  // Funeral Services
  "mortician",
  "funeral director",
  "embalmer",
  "crematorium operator",
  "funeral home manager",
  "funeral service coordinator",
  "cemetery manager",
  "memorial counselor",
  "grief counselor",
  "funeral arranger",

  // Miscellaneous Services
  "pet groomer",
  "dog walker",
  "pet sitter",
  "house sitter",
  "personal assistant",
  "errand runner",
  "professional organizer",
  "home stager",
  "move-in coordinator",
  "relocation specialist",
  "professional cuddler",
  "sleep consultant",
  "dating coach",
  "life coach",
  "career counselor",
  "resume writer",
  "genealogist",
  "personal historian",
  "professional listener",
  "decluttering specialist",
  "senator",
  "congressman",
  "parliamentarian",
  "political analyst",
  "campaign manager",
  "political consultant",
  "lobbyist",
  "political strategist",
  "election commissioner",
  "city council member",
  "mayor",
  "governor",
  "ambassador",
  "foreign minister",
  "defense minister",
  "cabinet secretary",
  "press secretary",
  "policy advisor",
  "legislative assistant",
  "political speech writer",
  "electoral officer",
  "constituency manager",
  "political party worker",
  "political campaign coordinator",
  "political fundraiser",
  "diplomatic attache",
  "foreign service specialist",
  "protocol officer",
  "public policy researcher",
  "legislative analyst",

  // Educational Administration
  "school superintendent",
  "education board member",
  "curriculum coordinator",
  "educational program director",
  "admissions officer",
  "registrar",
  "student affairs coordinator",
  "academic dean",
  "department chair",
  "education policy analyst",
  "distance learning coordinator",
  "special education coordinator",
  "student counseling director",
  "educational assessment specialist",
  "international education coordinator",
  "alumni relations manager",
  "education technology director",
  "school district administrator",
  "educational resource coordinator",
  "student services manager",

  // Performing Arts
  "ballet dancer",
  "contemporary dancer",
  "kathak dancer",
  "bharatanatyam dancer",
  "salsa instructor",
  "ballroom dance teacher",
  "dance company director",
  "opera singer",
  "classical vocalist",
  "playback singer",
  "orchestra conductor",
  "concert pianist",
  "violin virtuoso",
  "stage actor",
  "theater director",
  "drama coach",
  "mime artist",
  "puppeteer",
  "circus performer",
  "acrobat",
  "magician",
  "ventriloquist",
  "street performer",
  "performance artist",

  // Sports Administration & Coaching
  "sports team manager",
  "athletic director",
  "sports federation president",
  "sports event coordinator",
  "sports facility manager",
  "sports marketing director",
  "team physiotherapist",
  "sports nutritionist",
  "sports equipment manager",
  "sports broadcaster",
  "sports commentator",
  "sports journalist",
  "sports photographer",
  "sports statistician",
  "sports scout",
  "sports agent",
  "sports psychologist",
  "sports medicine physician",
  "sports rehabilitation specialist",
  "sports biomechanist",

  // Cultural & Heritage
  "museum curator",
  "art conservator",
  "heritage site manager",
  "cultural program director",
  "antiquities expert",
  "art appraiser",
  "cultural heritage specialist",
  "historical artifact restorer",
  "cultural tour guide",
  "cultural education coordinator",
  "folk art specialist",
  "traditional crafts instructor",
  "cultural research scholar",
  "ethnomusicologist",
  "cultural anthropologist",
  "textile conservator",
  "manuscript curator",
  "cultural events planner",
  "cultural policy advisor",
  "heritage conservation architect",

  // Fashion & Luxury
  "fashion merchandiser",
  "fashion buyer",
  "fashion forecaster",
  "textile designer",
  "pattern maker",
  "fashion illustrator",
  "runway coordinator",
  "fashion show director",
  "luxury brand manager",
  "personal shopper",
  "wardrobe consultant",
  "fashion photographer",
  "fashion journalist",
  "fashion public relations specialist",
  "costume supervisor",
  "jewelry designer",
  "accessories designer",
  "fashion startup consultant",
  "sustainable fashion specialist",
  "vintage fashion curator",

  // Digital & New Media
  "digital content creator",
  "podcaster",
  "streaming content manager",
  "social media influencer",
  "digital platform manager",
  "community manager",
  "digital rights manager",
  "virtual event coordinator",
  "digital asset manager",
  "online community moderator",
  "digital marketing strategist",
  "SEO specialist",
  "web accessibility consultant",
  "digital transformation consultant",
  "e-learning content creator",
  "virtual reality experience designer",
  "digital wellness coach",
  "digital ethics consultant",
  "digital inclusion specialist",
  "digital literacy educator",

  // Alternative Medicine & Wellness
  "ayurvedic practitioner",
  "homeopathic doctor",
  "acupuncturist",
  "naturopathic physician",
  "holistic health counselor",
  "meditation instructor",
  "reiki master",
  "aromatherapist",
  "herbalist",
  "traditional Chinese medicine practitioner",
  "wellness coach",
  "sound healing therapist",
  "crystal healing practitioner",
  "reflexologist",
  "hypnotherapist",
  "energy healer",
  "mindfulness trainer",
  "breathwork instructor",
  "ayurvedic massage therapist",
  "wellness retreat coordinator",

  // Culinary & Food Industry
  "food scientist",
  "flavor chemist",
  "food safety inspector",
  "culinary researcher",
  "food stylist",
  "recipe developer",
  "food critic",
  "wine sommelier",
  "tea sommelier",
  "coffee roaster",
  "craft beer brewer",
  "artisanal cheese maker",
  "chocolate maker",
  "food preservation specialist",
  "molecular gastronomy chef",
  "sustainable food systems analyst",
  "food waste reduction specialist",
  "urban farming consultant",
  "food security analyst",
  "culinary education director",

  // Animal Care & Wildlife
  "animal behaviorist",
  "wildlife rehabilitator",
  "exotic animal specialist",
  "marine mammal trainer",
  "zoo curator",
  "animal sanctuary manager",
  "wildlife photographer",
  "animal nutrition specialist",
  "pet psychologist",
  "animal welfare officer",
  "wildlife conservation officer",
  "endangered species specialist",
  "animal assisted therapy practitioner",
  "wildlife documentary maker",
  "animal shelter manager",
  "wildlife tour guide",
  "animal rescue coordinator",
  "wildlife research scientist",
  "animal breeding specialist",
  "wildlife habitat manager",

  // Urban Development & Planning
  "smart city planner",
  "urban sustainability consultant",
  "transportation planner",
  "public space designer",
  "urban agriculture specialist",
  "community development coordinator",
  "urban policy analyst",
  "housing development manager",
  "urban renewal specialist",
  "zoning administrator",
  "urban mobility consultant",
  "public infrastructure planner",
  "urban environmental specialist",
  "urban social worker",
  "community engagement coordinator",
  "urban safety consultant",
  "urban lighting designer",
  "urban noise consultant",
  "urban heat island specialist",
  "urban wildlife manager",

  // Emerging Technology
  "quantum software developer",
  "brain-computer interface engineer",
  "synthetic biology researcher",
  "autonomous vehicle systems engineer",
  "human-robot interaction specialist",
  "neural network architect",
  "edge computing specialist",
  "digital twin engineer",
  "biomimicry designer",
  "space habitat designer",
  "neural implant specialist",
  "quantum cryptography analyst",
  "molecular manufacturing engineer",
  "human augmentation specialist",
  "swarm robotics engineer",
  "bioprinting specialist",
  "neuromarketing analyst",
  "synthetic media specialist",
  "human-AI collaboration consultant",
  "quantum sensing engineer",

  // Social Impact & Development
  "social impact evaluator",
  "microfinance specialist",
  "fair trade certification specialist",
  "community organizer",
  "social enterprise consultant",
  "humanitarian aid coordinator",
  "disaster response specialist",
  "refugee support coordinator",
  "peace building facilitator",
  "conflict resolution specialist",
  "gender equality consultant",
  "indigenous rights advocate",
  "poverty alleviation specialist",
  "social inclusion coordinator",
  "human rights monitor",
  "child protection specialist",
  "disability rights advocate",
  "social justice educator",
  "community health worker",
  "grassroots movement coordinator",

  // Future of Work
  "remote work consultant",
  "digital nomad coach",
  "workplace culture specialist",
  "future of work strategist",
  "workforce transformation consultant",
  "hybrid workplace coordinator",
  "employee experience designer",
  "workplace wellness architect",
  "talent ecosystem manager",
  "workplace technology consultant",
  "organizational change specialist",
  "workplace diversity consultant",
  "workplace analytics specialist",
  "human-centered design consultant",
  "workplace sustainability coordinator",
  "workplace safety specialist",
  "workplace learning architect",
  "talent marketplace curator",
  "workplace innovation consultant",
  "workplace accessibility specialist",

  // Specialized Education
  "gifted education specialist",
  "learning disabilities specialist",
  "educational neuroscience researcher",
  "experiential learning facilitator",
  "environmental education specialist",
  "museum educator",
  "outdoor education specialist",
  "adult literacy instructor",
  "educational game designer",
  "educational content curator",
  "educational policy researcher",
  "educational technology innovator",
  "educational assessment designer",
  "educational program evaluator",
  "educational outreach coordinator",
  "educational materials developer",
  "educational research analyst",
  "educational grant writer",
  "educational quality assurance specialist",
  "educational standards coordinator",

  // Entertainment Industry
  "talent scout",
  "casting director",
  "entertainment lawyer",
  "celebrity manager",
  "entertainment marketing specialist",
  "live event producer",
  "entertainment publicist",
  "entertainment journalist",
  "entertainment critic",
  "entertainment industry analyst",
  "entertainment rights manager",
  "entertainment finance specialist",
  "entertainment risk assessor",
  "entertainment insurance specialist",
  "entertainment safety coordinator",
  "entertainment logistics manager",
  "entertainment technology specialist",
  "entertainment venue manager",
  "entertainment content strategist",
  "entertainment brand manager",

  // Space Industry
  "astrobiologist",
  "space mission planner",
  "spacecraft engineer",
  "space debris analyst",
  "space tourism coordinator",
  "space habitat architect",
  "space materials scientist",
  "space psychology researcher",
  "space agriculture specialist",
  "space medicine physician",
  "space law expert",
  "space policy analyst",
  "space ethics consultant",
  "space education specialist",
  "space safety officer",
  "space logistics coordinator",
  "space communications specialist",
  "space weather analyst",
  "space mining engineer",
  "space sustainability consultant",

  // Ocean & Marine
  "marine archaeologist",
  "underwater photographer",
  "marine conservation specialist",
  "coral reef restoration expert",
  "marine policy analyst",
  "marine renewable energy specialist",
  "marine biotechnology researcher",
  "marine pollution specialist",
  "marine education coordinator",
  "marine tourism guide",
  "marine safety instructor",
  "marine equipment specialist",
  "marine surveyor",
  "marine insurance assessor",
  "marine logistics coordinator",
  "marine research vessel operator",
  "marine wildlife observer",
  "marine protected area manager",
  "marine habitat restoration specialist",
  "marine citizen science coordinator",
  "software engineer",
  "frontend developer",
  "backend developer",
  "full stack developer",
  "mobile app developer",
  "iOS developer",
  "Android developer",
  "DevOps engineer",
  "site reliability engineer",
  "cloud architect",
  "systems architect",
  "database administrator",
  "data engineer",
  "machine learning engineer",
  "AI researcher",
  "quantum computing scientist",
  "blockchain developer",
  "smart contract developer",
  "game developer",
  "3D graphics programmer",
  "UI developer",
  "UX designer",
  "product designer",
  "web designer",
  "IT support specialist",
  "network administrator",
  "security analyst",
  "penetration tester",
  "cybersecurity engineer",
  "quality assurance engineer",
  "test automation engineer",
  "technical writer",
  "scrum master",
  "product owner",
  "project manager",
  "technology consultant",
  "systems analyst",
  "data scientist",
  "business intelligence analyst",
  "embedded systems engineer",
  "robotics engineer",
  "IoT developer",
  "AR/VR developer",

  // Healthcare
  "doctor",
  "surgeon",
  "cardiologist",
  "neurologist",
  "pediatrician",
  "psychiatrist",
  "dermatologist",
  "ophthalmologist",
  "dentist",
  "orthodontist",
  "nurse",
  "nurse practitioner",
  "registered nurse",
  "licensed practical nurse",
  "physician assistant",
  "pharmacist",
  "clinical pharmacist",
  "pharmacy technician",
  "physical therapist",
  "occupational therapist",
  "speech therapist",
  "radiologist",
  "radiologic technologist",
  "medical laboratory technician",
  "pathologist",
  "anesthesiologist",
  "emergency medical technician",
  "paramedic",
  "nutritionist",
  "dietitian",
  "chiropractor",
  "optometrist",
  "audiologist",
  "midwife",
  "veterinarian",
  "veterinary technician",
  "medical researcher",
  "biomedical engineer",
  "genetic counselor",
  "mental health counselor",
  "psychologist",
  "clinical psychologist",
  "sports psychologist",

  // Education
  "teacher",
  "professor",
  "assistant professor",
  "associate professor",
  "lecturer",
  "kindergarten teacher",
  "elementary school teacher",
  "middle school teacher",
  "high school teacher",
  "special education teacher",
  "music teacher",
  "art teacher",
  "physical education teacher",
  "ESL teacher",
  "language instructor",
  "curriculum developer",
  "educational consultant",
  "school counselor",
  "school psychologist",
  "school administrator",
  "principal",
  "dean",
  "academic advisor",
  "librarian",
  "research assistant",
  "teaching assistant",
  "education technology specialist",
  "corporate trainer",
  "instructional designer",
  "early childhood educator",

  // Legal
  "lawyer",
  "attorney",
  "corporate lawyer",
  "criminal defense lawyer",
  "civil rights lawyer",
  "patent attorney",
  "intellectual property lawyer",
  "tax lawyer",
  "immigration lawyer",
  "family law attorney",
  "real estate lawyer",
  "environmental lawyer",
  "judge",
  "magistrate",
  "legal clerk",
  "paralegal",
  "legal assistant",
  "court reporter",
  "mediator",
  "arbitrator",
  "legal consultant",
  "compliance officer",
  "regulatory affairs specialist",

  // Business & Finance
  "accountant",
  "certified public accountant",
  "tax accountant",
  "forensic accountant",
  "financial analyst",
  "investment banker",
  "financial advisor",
  "wealth manager",
  "portfolio manager",
  "hedge fund manager",
  "venture capitalist",
  "private equity associate",
  "business analyst",
  "management consultant",
  "strategy consultant",
  "chief executive officer",
  "chief financial officer",
  "chief operating officer",
  "chief technology officer",
  "chief marketing officer",
  "chief human resources officer",
  "operations manager",
  "project coordinator",
  "business development manager",
  "sales manager",
  "account executive",
  "marketing manager",
  "digital marketing specialist",
  "social media manager",
  "content strategist",
  "public relations specialist",
  "human resources manager",
  "recruiter",
  "talent acquisition specialist",
  "compensation analyst",
  "benefits coordinator",
  "risk analyst",
  "insurance underwriter",
  "actuary",
  "economist",
  "market research analyst",

  // Engineering
  "civil engineer",
  "structural engineer",
  "mechanical engineer",
  "electrical engineer",
  "chemical engineer",
  "aerospace engineer",
  "automotive engineer",
  "industrial engineer",
  "manufacturing engineer",
  "materials engineer",
  "environmental engineer",
  "mining engineer",
  "petroleum engineer",
  "nuclear engineer",
  "biomedical engineer",
  "architectural engineer",
  "safety engineer",
  "quality engineer",
  "process engineer",
  "systems engineer",
  "control systems engineer",
  "RF engineer",
  "power systems engineer",
  "HVAC engineer",
  "acoustical engineer",
  "marine engineer",
  "agricultural engineer",

  // Creative & Media
  "graphic designer",
  "art director",
  "creative director",
  "illustrator",
  "animator",
  "3D artist",
  "motion graphics designer",
  "photographer",
  "videographer",
  "film director",
  "producer",
  "video editor",
  "sound engineer",
  "audio engineer",
  "music producer",
  "composer",
  "musician",
  "actor",
  "voice actor",
  "screenwriter",
  "copywriter",
  "content writer",
  "journalist",
  "reporter",
  "news anchor",
  "editor",
  "publisher",
  "fashion designer",
  "interior designer",
  "industrial designer",
  "exhibition designer",
  "set designer",
  "costume designer",
  "makeup artist",
  "hair stylist",

  // Construction & Architecture
  "architect",
  "landscape architect",
  "urban planner",
  "construction manager",
  "general contractor",
  "carpenter",
  "electrician",
  "plumber",
  "mason",
  "painter",
  "roofer",
  "welder",
  "crane operator",
  "heavy equipment operator",
  "surveyor",
  "building inspector",
  "estimator",
  "project superintendent",
  "site manager",
  "facilities manager",

  // Science & Research
  "scientist",
  "research scientist",
  "physicist",
  "chemist",
  "biologist",
  "microbiologist",
  "biochemist",
  "geologist",
  "meteorologist",
  "oceanographer",
  "astronomer",
  "archaeologist",
  "anthropologist",
  "zoologist",
  "botanist",
  "environmental scientist",
  "food scientist",
  "materials scientist",
  "forensic scientist",
  "research associate",
  "laboratory technician",
  "clinical research coordinator",

  // Aviation & Transportation
  "pilot",
  "commercial pilot",
  "airline pilot",
  "helicopter pilot",
  "flight instructor",
  "air traffic controller",
  "aircraft mechanic",
  "avionics technician",
  "flight attendant",
  "ground crew",
  "train conductor",
  "locomotive engineer",
  "ship captain",
  "marine navigator",
  "merchant marine",
  "truck driver",
  "bus driver",
  "taxi driver",
  "delivery driver",
  "logistics coordinator",
  "supply chain manager",
  "freight forwarder",

  // Hospitality & Service
  "chef",
  "executive chef",
  "sous chef",
  "pastry chef",
  "line cook",
  "restaurant manager",
  "hotel manager",
  "concierge",
  "event planner",
  "wedding planner",
  "travel agent",
  "tour guide",
  "flight booking agent",
  "bartender",
  "sommelier",
  "barista",
  "waiter",
  "waitress",
  "host",
  "hostess",
  "housekeeper",
  "custodian",
  "janitor",

  // Agriculture & Environmental
  "farmer",
  "agricultural manager",
  "agronomist",
  "horticulturist",
  "viticulturist",
  "aquaculturist",
  "fish farmer",
  "forester",
  "conservation officer",
  "park ranger",
  "wildlife biologist",
  "environmental consultant",
  "sustainability consultant",
  "renewable energy specialist",
  "waste management specialist",
  "recycling coordinator",
  "landscaper",
  "groundskeeper",
  "arborist",
  "pest control specialist",

  // Public Service & Government
  "police officer",
  "detective",
  "firefighter",
  "paramedic",
  "military officer",
  "soldier",
  "diplomat",
  "foreign service officer",
  "intelligence analyst",
  "postal worker",
  "mail carrier",
  "civil servant",
  "government administrator",
  "policy analyst",
  "urban planner",
  "social worker",
  "probation officer",
  "customs officer",
  "immigration officer",
  "tax examiner",

  // Sports & Fitness
  "athlete",
  "professional athlete",
  "sports coach",
  "personal trainer",
  "fitness instructor",
  "yoga instructor",
  "pilates instructor",
  "athletic trainer",
  "sports therapist",
  "sports psychologist",
  "sports agent",
  "sports scout",
  "referee",
  "umpire",
  "lifeguard",
  "swimming instructor",
  "dance instructor",
  "choreographer",
  "martial arts instructor",
  "gym manager",

  // Beauty & Personal Care
  "hairdresser",
  "barber",
  "cosmetologist",
  "esthetician",
  "nail technician",
  "massage therapist",
  "spa manager",
  "beauty consultant",
  "makeup artist",
  "skincare specialist",
  "tattoo artist",
  "permanent makeup artist",
  "hair colorist",
  "beauty salon owner",

  // Religious & Spiritual
  "clergy",
  "priest",
  "minister",
  "rabbi",
  "imam",
  "monk",
  "nun",
  "chaplain",
  "missionary",
  "religious educator",
  "pastoral counselor",
  "youth minister",
  "religious administrator",
  "spiritual advisor",

  // Skilled Trades
  "machinist",
  "tool and die maker",
  "millwright",
  "boilermaker",
  "sheet metal worker",
  "glazier",
  "insulation installer",
  "locksmith",
  "watchmaker",
  "jeweler",
  "upholsterer",
  "tailor",
  "seamstress",
  "cobbler",
  "cabinet maker",
  "furniture maker",
  "woodworker",
  "blacksmith",
  "gunsmith",
  "elevator installer",
  "HVAC technician",
  "appliance repair technician",
  "auto mechanic",
  "diesel mechanic",
  "motorcycle mechanic",
  "bicycle mechanic",
  "small engine repair technician",

  // Emerging & Specialized
  "drone operator",
  "robotics technician",
  "3D printing specialist",
  "virtual reality designer",
  "augmented reality developer",
  "cryptocurrency analyst",
  "blockchain consultant",
  "digital forensics specialist",
  "ethical hacker",
  "cloud security architect",
  "quantum computing researcher",
  "nanotechnology engineer",
  "biotechnology researcher",
  "gene therapy specialist",
  "space systems engineer",
  "asteroid mining engineer",
  "vertical farming specialist",
  "sustainable energy consultant",
  "carbon capture technologist",
  "climate change analyst",
  "senator",
  "congressman",
  "parliamentarian",
  "political analyst",
  "campaign manager",
  "political consultant",
  "lobbyist",
  "political strategist",
  "election commissioner",
  "city council member",
  "mayor",
  "governor",
  "ambassador",
  "foreign minister",
  "defense minister",
  "cabinet secretary",
  "press secretary",
  "policy advisor",
  "legislative assistant",
  "political speech writer",
  "electoral officer",
  "constituency manager",
  "political party worker",
  "political campaign coordinator",
  "political fundraiser",
  "diplomatic attache",
  "foreign service specialist",
  "protocol officer",
  "public policy researcher",
  "legislative analyst",

  // Educational Administration
  "school superintendent",
  "education board member",
  "curriculum coordinator",
  "educational program director",
  "admissions officer",
  "registrar",
  "student affairs coordinator",
  "academic dean",
  "department chair",
  "education policy analyst",
  "distance learning coordinator",
  "special education coordinator",
  "student counseling director",
  "educational assessment specialist",
  "international education coordinator",
  "alumni relations manager",
  "education technology director",
  "school district administrator",
  "educational resource coordinator",
  "student services manager",

  // Performing Arts
  "ballet dancer",
  "contemporary dancer",
  "kathak dancer",
  "bharatanatyam dancer",
  "salsa instructor",
  "ballroom dance teacher",
  "dance choreographer",
  "dance company director",
  "opera singer",
  "classical vocalist",
  "playback singer",
  "orchestra conductor",
  "concert pianist",
  "violin virtuoso",
  "stage actor",
  "theater director",
  "drama coach",
  "mime artist",
  "puppeteer",
  "circus performer",
  "acrobat",
  "magician",
  "ventriloquist",
  "street performer",
  "performance artist",

  // Sports Administration & Coaching
  "sports team manager",
  "athletic director",
  "sports federation president",
  "sports event coordinator",
  "sports facility manager",
  "sports marketing director",
  "team physiotherapist",
  "sports nutritionist",
  "sports equipment manager",
  "sports broadcaster",
  "sports commentator",
  "sports journalist",
  "sports photographer",
  "sports statistician",
  "sports scout",
  "sports agent",
  "sports psychologist",
  "sports medicine physician",
  "sports rehabilitation specialist",
  "sports biomechanist",

  // Cultural & Heritage
  "museum curator",
  "art conservator",
  "heritage site manager",
  "cultural program director",
  "antiquities expert",
  "art appraiser",
  "cultural heritage specialist",
  "historical artifact restorer",
  "cultural tour guide",
  "cultural education coordinator",
  "folk art specialist",
  "traditional crafts instructor",
  "cultural research scholar",
  "ethnomusicologist",
  "cultural anthropologist",
  "textile conservator",
  "manuscript curator",
  "cultural events planner",
  "cultural policy advisor",
  "heritage conservation architect",

  // Fashion & Luxury
  "fashion merchandiser",
  "fashion buyer",
  "fashion forecaster",
  "textile designer",
  "pattern maker",
  "fashion illustrator",
  "runway coordinator",
  "fashion show director",
  "luxury brand manager",
  "personal shopper",
  "wardrobe consultant",
  "fashion photographer",
  "fashion journalist",
  "fashion public relations specialist",
  "costume supervisor",
  "jewelry designer",
  "accessories designer",
  "fashion startup consultant",
  "sustainable fashion specialist",
  "vintage fashion curator",

  // Digital & New Media
  "digital content creator",
  "podcaster",
  "streaming content manager",
  "social media influencer",
  "digital platform manager",
  "community manager",
  "digital rights manager",
  "virtual event coordinator",
  "digital asset manager",
  "online community moderator",
  "digital marketing strategist",
  "SEO specialist",
  "web accessibility consultant",
  "digital transformation consultant",
  "e-learning content creator",
  "virtual reality experience designer",
  "digital wellness coach",
  "digital ethics consultant",
  "digital inclusion specialist",
  "digital literacy educator",

  // Alternative Medicine & Wellness
  "ayurvedic practitioner",
  "homeopathic doctor",
  "acupuncturist",
  "naturopathic physician",
  "holistic health counselor",
  "meditation instructor",
  "reiki master",
  "aromatherapist",
  "herbalist",
  "traditional Chinese medicine practitioner",
  "wellness coach",
  "sound healing therapist",
  "crystal healing practitioner",
  "reflexologist",
  "hypnotherapist",
  "energy healer",
  "mindfulness trainer",
  "breathwork instructor",
  "ayurvedic massage therapist",
  "wellness retreat coordinator",

  // Culinary & Food Industry
  "food scientist",
  "flavor chemist",
  "food safety inspector",
  "culinary researcher",
  "food stylist",
  "recipe developer",
  "food critic",
  "wine sommelier",
  "tea sommelier",
  "coffee roaster",
  "craft beer brewer",
  "artisanal cheese maker",
  "chocolate maker",
  "food preservation specialist",
  "molecular gastronomy chef",
  "sustainable food systems analyst",
  "food waste reduction specialist",
  "urban farming consultant",
  "food security analyst",
  "culinary education director",

  // Animal Care & Wildlife
  "animal behaviorist",
  "wildlife rehabilitator",
  "exotic animal specialist",
  "marine mammal trainer",
  "zoo curator",
  "animal sanctuary manager",
  "wildlife photographer",
  "animal nutrition specialist",
  "pet psychologist",
  "animal welfare officer",
  "wildlife conservation officer",
  "endangered species specialist",
  "animal assisted therapy practitioner",
  "wildlife documentary maker",
  "animal shelter manager",
  "wildlife tour guide",
  "animal rescue coordinator",
  "wildlife research scientist",
  "animal breeding specialist",
  "wildlife habitat manager",

  // Urban Development & Planning
  "smart city planner",
  "urban sustainability consultant",
  "transportation planner",
  "public space designer",
  "urban agriculture specialist",
  "community development coordinator",
  "urban policy analyst",
  "housing development manager",
  "urban renewal specialist",
  "zoning administrator",
  "urban mobility consultant",
  "public infrastructure planner",
  "urban environmental specialist",
  "urban social worker",
  "community engagement coordinator",
  "urban safety consultant",
  "urban lighting designer",
  "urban noise consultant",
  "urban heat island specialist",
  "urban wildlife manager",

  // Emerging Technology
  "quantum software developer",
  "brain-computer interface engineer",
  "synthetic biology researcher",
  "autonomous vehicle systems engineer",
  "human-robot interaction specialist",
  "neural network architect",
  "edge computing specialist",
  "digital twin engineer",
  "biomimicry designer",
  "space habitat designer",
  "neural implant specialist",
  "quantum cryptography analyst",
  "molecular manufacturing engineer",
  "human augmentation specialist",
  "swarm robotics engineer",
  "bioprinting specialist",
  "neuromarketing analyst",
  "synthetic media specialist",
  "human-AI collaboration consultant",
  "quantum sensing engineer",

  // Social Impact & Development
  "social impact evaluator",
  "microfinance specialist",
  "fair trade certification specialist",
  "community organizer",
  "social enterprise consultant",
  "humanitarian aid coordinator",
  "disaster response specialist",
  "refugee support coordinator",
  "peace building facilitator",
  "conflict resolution specialist",
  "gender equality consultant",
  "indigenous rights advocate",
  "poverty alleviation specialist",
  "social inclusion coordinator",
  "human rights monitor",
  "child protection specialist",
  "disability rights advocate",
  "social justice educator",
  "community health worker",
  "grassroots movement coordinator",

  // Future of Work
  "remote work consultant",
  "digital nomad coach",
  "workplace culture specialist",
  "future of work strategist",
  "workforce transformation consultant",
  "hybrid workplace coordinator",
  "employee experience designer",
  "workplace wellness architect",
  "talent ecosystem manager",
  "workplace technology consultant",
  "organizational change specialist",
  "workplace diversity consultant",
  "workplace analytics specialist",
  "human-centered design consultant",
  "workplace sustainability coordinator",
  "workplace safety specialist",
  "workplace learning architect",
  "talent marketplace curator",
  "workplace innovation consultant",
  "workplace accessibility specialist",

  // Specialized Education
  "gifted education specialist",
  "learning disabilities specialist",
  "educational neuroscience researcher",
  "experiential learning facilitator",
  "environmental education specialist",
  "museum educator",
  "outdoor education specialist",
  "adult literacy instructor",
  "educational game designer",
  "educational content curator",
  "educational policy researcher",
  "educational technology innovator",
  "educational assessment designer",
  "educational program evaluator",
  "educational outreach coordinator",
  "educational materials developer",
  "educational research analyst",
  "educational grant writer",
  "educational quality assurance specialist",
  "educational standards coordinator",

  // Entertainment Industry
  "talent scout",
  "casting director",
  "entertainment lawyer",
  "celebrity manager",
  "entertainment marketing specialist",
  "live event producer",
  "entertainment publicist",
  "entertainment journalist",
  "entertainment critic",
  "entertainment industry analyst",
  "entertainment rights manager",
  "entertainment finance specialist",
  "entertainment risk assessor",
  "entertainment insurance specialist",
  "entertainment safety coordinator",
  "entertainment logistics manager",
  "entertainment technology specialist",
  "entertainment venue manager",
  "entertainment content strategist",
  "entertainment brand manager",

  // Space Industry
  "astrobiologist",
  "space mission planner",
  "spacecraft engineer",
  "space debris analyst",
  "space tourism coordinator",
  "space habitat architect",
  "space materials scientist",
  "space psychology researcher",
  "space agriculture specialist",
  "space medicine physician",
  "space law expert",
  "space policy analyst",
  "space ethics consultant",
  "space education specialist",
  "space safety officer",
  "space logistics coordinator",
  "space communications specialist",
  "space weather analyst",
  "space mining engineer",
  "space sustainability consultant",

  // Ocean & Marine
  "marine archaeologist",
  "underwater photographer",
  "marine conservation specialist",
  "coral reef restoration expert",
  "marine policy analyst",
  "marine renewable energy specialist",
  "marine biotechnology researcher",
  "marine pollution specialist",
  "marine education coordinator",
  "marine tourism guide",
  "marine safety instructor",
  "marine equipment specialist",
  "marine surveyor",
  "marine insurance assessor",
  "marine logistics coordinator",
  "marine research vessel operator",
  "marine wildlife observer",
  "marine protected area manager",
  "marine habitat restoration specialist",
  "marine citizen science coordinator",
];
