import { INavOptions } from "../types";
import { LOCATIONS } from "./locations";
import Config from "react-native-config";

export const COMMUNITY_NAME = Config.COMMUNITY_NAME || "Bhumihar Family";

export const APP_NAME = Config.APP_NAME || "Bhumihar Family";

export const API_BASE_URL =
  Config.API_BASE_URL || "https://bhumiharfamily.com";
  // Config.API_BASE_URL || "http://localhost:8000";
  
export const ROUTES = {
  HOME: "Home",
  LOGIN: "Login",
  SIGNUP: "Signup",
  FORGET_PASSWORD: "ForgetPassword",
  ONBOARDING: "Onboarding",
  SOCIAL: "Social",
  PROFILE: "Profile",
  MATCHES: "Matches",
  SETTINGS: "Settings",
  COMMUNITY: "Community",
  POSTS: "Posts",
  MATRIMONIAL: "Matrimonial",
  CHAT: "Chat",
} as const;

export const STORAGE_KEYS = {
  AUTH_TOKEN: "@auth_token",
  REFRESH_TOKEN: "@refresh_token",
  USER_DATA: "@user_data",
  THEME: "@theme",
  REGISTER_SECRET_KEY: "@register_secret_key",
  FORGET_PASS_SECRET_KEY: "@forget_pass_secret_key",
} as const;


export const EDUCATION_DEGREES = [
  "B.A",
  "B.Com",
  "B.E/B.Tech",
  "B.Pharma",
  "B.Sc",
  "L.L.B",
  "MBBS",
  "Other",
  "BAMS",
  "BHMS",
  "BDS",
  "BVSc.",
  "BCA",
  "B.IT",
  "B.Arch",
  "BBA",
  "BHM",
  "B.Ed",
  "BPT",
  "BFA",
  "BJMC",
  "B.Des",
  "B.Agri.",
  "BAM",
  "B.A. LL.B.",
  "B.A. LL.B. (Hons)",
  "B.A. (Hons)",
  "BBI",
  "BBA LL.B.",
  "BBA LL.B. (Hons)",
  "BBE",
  "BBM",
  "BCVT",
  "BCT & CA",
  "B.Com LL.B",
  "B.Com (Hons)",
  "B.El.Ed",
  "B.FAD",
  "B.FTech",
  "BFM",
  "B.F.Sc.",
  "BFT",
  "B.H.A.",
  "BHMCT",
  "BHMTT",
  "BID",
  "B.J.",
  "B.L.S. LL.B.",
  "B.Lib.I.Sc.",
  "B.Lib.Sc.",
  "B.Litt",
  "BMS",
  "B.M.C.",
  "B.M.M.",
  "B.M.M.M.C.",
  "BMLT",
  "BMRIT",
  "BMRT",
  "B.Mus.",
  "BNYS",
  "BOT",
  "B.O.Th",
  "BOPTM",
  "BPMT",
  "BPA",
  "B.P.Ed",
  "B.P.E.S",
  "BPO",
  "BPH",
  "BRDIT",
  "B.Sc. (Post Basic)",
  "BSW",
  "B.Tech LL.B.",
  "BUMS",
  "BVA",
  "B.Voc",
  "CA",
  "CS",
  "ICWA",
  "M.A",
  "M.Com",
  "M.E/M.Tech",
  "M.Pharma",
  "M.Sc",
  "MBA/PGDM",
  "MCA",
  "M.D.",
  "L.L.M.",
  "M.S. (Engineering)",
  "M.S. (Medicine)",
  "MVSc.",
  "M.Arch",
  "CFA",
  "M.Ed",
  "MDS",
  "MPT",
  "DM",
  "MCh",
  "MSW",
  "MFA",
  "MJMC",
  "M.Des",
  "MAM",
  "MBE",
  "MBF",
  "M.B.L",
  "M.FTech",
  "MFC",
  "MFM",
  "M.F.Sc.",
  "M.H.Sc.",
  "MHA",
  "MID",
  "MIB",
  "M.J.",
  "M.Lib.I.Sc.",
  "M.Lib.Sc.",
  "MMS",
  "MMM",
  "M.M.C.",
  "MOT",
  "M.Optom.",
  "M.O.L.",
  "MPA",
  "M.P.Ed",
  "M.Plan",
  "MPH",
  "MS",
  "MTM",
  "MTA",
  "MTM",
  "MVA",
  "M.Voc",
  "MHRM",
  "MBM",
  "MCM",
  "Executive MBA/PGDM",
  "PGDCA",
  "PhD",
  "M.Phil",
  "LL.D.",
  "D.Litt",
  "Pharm.D",
];

export const SPECIALIZED_DEGREES = [
  "Computer Science",
  "Information Technology",
  "Electronics",
  "Mechanical",
  "Civil",
  "Electrical",
  "Chemical",
  "Aerospace",
  "Physics",
  "Chemistry",
  "Biology",
  "Mathematics",
  "Environmental Science",
  "Accounting",
  "Finance",
  "Banking",
  "Economics",
  "Business Administration",
  "Psychology",
  "Sociology",
  "Literature",
  "History",
  "Political Science",
  "Medicine",
  "Dentistry",
  "Pharmacy",
  "Nursing",
  "Physiotherapy",
];

export const PROFESSIONS = [
  // Healthcare Professionals
  "Doctor",
  "Nurse",
  "Dentist",
  "Eye Doctor",
  "Physiotherapist",
  "Traditional Healer (Vaid/Hakeem)",
  "Mental Health Counselor",
  "Veterinarian",
  "Pharmacist",
  "Paramedic",
  "Midwife",

  // Education Professionals
  "Teacher",
  "Tutor",
  "Professor",
  "Sports Coach",
  "Music Teacher",
  "Dance Instructor",
  "Art Teacher",
  "Language Instructor",
  "Computer Trainer",
  "Driving Instructor",

  // Skilled Trade Workers
  "Electrician",
  "Plumber",
  "Carpenter",
  "Painter",
  "Mason",
  "Welder",
  "AC Repair Technician",
  "TV Repair Technician",
  "Mobile Phone Repair Technician",
  "Watch Repairer",
  "Tailor",
  "Cobbler (Mochi)",

  // Service Providers
  "Security Guard",
  "House Help/Maid",
  "Cook",
  "Driver",
  "Delivery Person",
  "Cleaner",
  "Gardener",
  "Beautician",
  "Barber",
  "Masseur",
  "Baby Sitter",
  "Elder Care Provider",

  // Government Officials
  "Police Officer",
  "Tehsildar",
  "Patwari",
  "Collector",
  "MLA",
  "MP",
  "Gram Pradhan",
  "Sarpanch",
  "Municipal Worker",
  "Government Clerk",

  // Legal Professionals
  "Lawyer",
  "Notary",
  "Legal Consultant",
  "Document Writer",
  "Property Dealer",

  // Financial Services
  "Bank Employee",
  "Insurance Agent",
  "Financial Advisor",
  "Accountant",
  "Tax Consultant",
  "Money Lender",

  // Religious Services
  "Priest (Pandit)",
  "Maulvi",
  "Religious Teacher",
  "Astrologer",
  "Palm Reader",

  // Transportation Workers
  "Auto Driver",
  "Taxi Driver",
  "Bus Driver",
  "Train Driver",
  "Porter (Coolie)",
  "Rickshaw Puller",

  // Small Business Owners
  "Shop Owner",
  "Restaurant Owner",
  "Street Vendor",
  "Vegetable Seller",
  "Milk Vendor",
  "Newspaper Vendor",
  "Tea Stall Owner",

  // Entertainment & Arts
  "Musician",
  "Singer",
  "Dancer",
  "Actor",
  "Photographer",
  "Videographer",
  "Wedding Planner",
  "Event Organizer",

  // Maintenance Services
  "Pest Control Worker",
  "Building Maintenance Worker",
  "Water Tank Cleaner",
  "Solar Panel Technician",
  "CCTV Technician",
  "Elevator Technician",

  // Agricultural Workers
  "Farmer",
  "Farm Laborer",
  "Nursery Worker",
  "Animal Husbandry Worker",
  "Agricultural Consultant",

  // Specialty Services
  "Translation Service Provider",
  "Fitness Trainer",
  "Career Counselor",
  "Travel Agent",
  "Real Estate Agent",
  "Interior Designer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Backend Engineer",
  "Software Developer",
  "UI/UX Designer",
  "Project Manager",
  "Data Scientist",
];

export const HOBBIES = [
  "Reading",
  "Writing",
  "Photography",
  "Painting",
  "Music",
  "Dancing",
  "Cooking",
  "Traveling",
  "Gaming",
  "Sports",
  "Yoga",
  "Meditation",
  "Gardening",
  "Hiking",
  "Swimming",
  "Other",
];

export const SKILLS = [
  // Technical Skills
  "Programming",
  "Web Development",
  "Mobile Development",
  "Data Analysis",
  "Machine Learning",
  "Cloud Computing",
  "Digital Marketing",
  "Graphic Design",
  "Project Management",
  // Soft Skills
  "Leadership",
  "Communication",
  "Problem Solving",
  "Team Management",
  "Time Management",
  "Critical Thinking",
  "Creativity",
  "Adaptability",
  "Other",
];

export const LANGUAGES: string[] = [
  "English",
  "Assamese",
  "Bengali",
  "Bodo",
  "Dogri",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Kashmiri",
  "Konkani",
  "Maithili",
  "Malayalam",
  "Manipuri",
  "Marathi",
  "Nepali",
  "Odia",
  "Punjabi",
  "Sanskrit",
  "Santali",
  "Sindhi",
  "Tamil",
  "Telugu",
  "Urdu",
  "Tamil",
  "Sanskrit",
  "Kannada",
  "Telugu",
  "Malayalam",
  "Odia",
  "Tulu",
  "Gondi",
  "Ho",
  "Khasi",
  "Mundari",
  "Kui",
  "Kurukh",
  "Mizo",
  "Bishnupriya Manipuri",
  "Meitei (Manipuri)",
  "Garhwali",
  "Kumaoni",
  "Bhili",
  "Lepcha",
  "Sherpa",
  "Ladakhi",
  "Pahari",
  "Chhattisgarhi",
  "Magahi",
  "Angika",
  "Bhojpuri",
  "Marwari",
  "Rajasthani",
  "Ahirani",
  "Bagheli",
  "Bundeli",
  "Awadhi",
  "Chhattisgarhi",
  "Lambadi",
  "Sora",
  "Koya",
  "Kui",
  "Kodava",
  "Malvi",
  "Santali",
  "Ho",
  "Kurukh",
  "Gondi",
  "Kharia",
  "Mundari",
  "Kui",
  "Bhili",
  "Oraon",
  "Korwa",
  "Korku",
  "Bhilali",
  "Lodha",
  "Mishing",
  "Nicobarese",
  "Shompeng",
  "Toda",
  "Irula",
  "Juang",
  "Saura",
  "Bodo",
  "Dimasa",
  "Karbi",
  "Rabha",
  "Mizo",
  "Lushai",
  "Hmar",
  "Tangkhul",
  "Meitei",
  "Thadou",
  "Paite",
  "Ao",
  "Angami",
  "Sumi",
  "Lotha",
  "Rengma",
  "Phom",
  "Chakhesang",
  "Zeme",
  "Pochury",
  "Chang",
];

export const CASTES = ["Bhumihar"];

export const INCOME_RANGES = [
  "Below ₹5 lakhs",
  "₹5-10 lakhs",
  "₹10-15 lakhs",
  "₹15-20 lakhs",
  "₹20-30 lakhs",
  "₹30-50 lakhs",
  "Above ₹50 lakhs",
];

export const BODY_TYPES = ["Athletic", "Average", "Slim", "Heavy", "Other"];

export const NATIONALITIES = [
  "Indian",
  "American",
  "British",
  "Canadian",
  "Australian",
  "Other",
];

export interface INavOptions {
  id: number;
  label: string;
  screen: string; // ✅ path nahi, screen
}

export const NAVIGATION_OPTIONS: INavOptions[] = [
  {
    id: 1,
    label: "Dashboard",
    screen: "Home",
  },
  {
    id: 4,
    label: "Social Media",
    screen: "Social",
  },
  {
    id: 2,
    label: "Community",
    screen: "CommunityRoutes",
  },
  {
    id: 3,
    label: "Matrimonial",
    screen: "MatrimonialRoutes",
  },
  {
    id: 5,
    label: "Chat",
    screen: "ChatRoutes",
  },
];

interface NavigationItem {
  item: string;
  screen: string;
}

interface NavigationSection {
  label: string;
  children: NavigationItem[];
}

export const NAVIGATIONS: NavigationSection[] = [
  {
    label: "Dashboard",
    children: [
      {
        item: "Home",
        screen: "Home",
      },
    ],
  },
  {
    label: "Social Media",
    children: [
      {
        item: "Posts",
        screen: "Post",
      },
    ],
  },
  {
    label: "Community",
    children: [
      {
        item: "Home",
        screen: "CommunityHome",
      },
      {
        item: "Seekers",
        screen: "Seekers",
      },
      {
        item: "Helpers",
        screen: "Helpers",
      },
    ],
  },
  {
    label: "Matrimonial",
    children: [
      {
        item: "Matches",
        screen: "MatrimonialHome",
      },
      {
        item: "Search",
        screen: "Search",
      },
      {
        item: "Sent Interests",
        screen: "SentInterest",
      },
    ],
  },
  {
    label: "Chat",
    children: [
      {
        item: "Inbox",
        screen: "ChatHome",
      },
    ],
  },
];

export const STATES: string[] = Object.keys(LOCATIONS);

export const OCCUPATIONS: string[] = [
  "Doesn't Matter",
  "Private Sector",
  "Government/Public Sector",
  "Civil Services",
  "Defence",
  "Business/ Self Employed",
  "Not Working",
  "Banking & Finance",
  "Accounting Professional",
  "Auditor",
  "Banking Professional",
  "Chartered Accountant",
  "Finance Professional",
  "Advertising, Media & Entertainment",
  "Actor/Model",
  "Advertising Professional",
  "Film/ Entertainment Professional",
  "Journalist",
  "Media Professional",
  "PR Professional",
  "Administration",
  "Admin Professional",
  "Clerk",
  "Operator/Technician",
  "Secretary/Front Office",
  "Others",
  "Agent",
  "Artist",
  "Beautician",
  "Broker",
  "Business Owner/ Entrepreneur",
  "Businessperson",
  "Fashion Designer",
  "Fitness Professional",
  "Interior Designer",
  "Others",
  "Politician",
  "Security Professional",
  "Singer",
  "Social Services/ NGO/ Volunteer",
  "Sportsperson",
  "Travel Professional",
  "Writer",
  "Agricultural",
  "Agriculture Professional",
  "Farming",
  "Armed Forces",
  "Air Force",
  "Army",
  "Defence Services",
  "Navy",
  "Airline & Aviation",
  "Airline Professional",
  "Flight Attendant",
  "Pilot",
  "Corporate Management Professionals",
  "Analyst",
  "Consultant",
  "Corporate Communication",
  "Corporate Planning",
  "HR Professional",
  "Marketing Professional",
  "Operations Management",
  "Product manager",
  "Program Manager",
  "Project Manager - IT",
  "Project Manager - Non IT",
  "Sales Professional",
  "Sr. Manager/ Manager",
  "Subject Matter Expert",
  "Software & IT",
  "Animator",
  "Cyber/Network Security",
  "Project Lead - IT",
  "Quality Assurance Engineer - IT",
  "Software Professional",
  "UI/UX designer",
  "Web/Graphic Designer",
  "Architecture",
  "Architect",
  "BPO & Customer Service",
  "BPO/ITes Professional",
  "Customer Service",
  "Civil Services",
  "Civil Services (IAS/ IPS/ IRS/ IES/ IFS)",
  "Top Management",
  "CxO/ Chairman/ President/ Director",
  "VP/ AVP/ GM/ DGM",
  "Doctor",
  "Dentist",
  "Doctor",
  "Surgeon",
  "Education & Training",
  "Education Professional",
  "Educational Institution Owner",
  "Librarian",
  "Professor/Lecturer",
  "Research Assistant",
  "Teacher",
  "Engineering",
  "Electronics Engineer",
  "Hardware/Telecom Engineer",
  "Non - IT Engineer",
  "Quality Assurance Engineer",
  "Hospitality",
  "Hotels/Hospitality Professional",
  "Law Enforcement",
  "Law Enforcement Officer",
  "Police",
  "Legal",
  "Lawyer & Legal Professional",
  "Not working",
  "Looking for job",
  "Not working",
  "Retired",
  "Student",
  "Merchant Navy",
  "Mariner",
  "Merchant Naval Officer",
  "Other Medical & Healthcare",
  "Medical/ Healthcare Professional",
  "Nurse",
  "Paramedic",
  "Pharmacist",
  "Physiotherapist",
  "Psychologist",
  "Veterinary Doctor",
  "Science & Research",
  "Research Professional",
  "Science Professional",
  "Scientist",
];

export const SECTORS: string[] = [
  // Primary Sectors
  "Agriculture",
  "Fishing",
  "Forestry",
  "Mining",
  "Quarrying",
  "Hunting",
  "Livestock Farming",
  "Oil and Gas Extraction",
  "Metal Ore Mining",

  // Manufacturing
  "Automotive Manufacturing",
  "Aerospace and Defense",
  "Electronics Manufacturing",
  "Pharmaceutical Manufacturing",
  "Textile and Apparel",
  "Food Processing",
  "Chemical Manufacturing",
  "Machinery and Equipment",
  "Semiconductor Production",
  "Furniture Manufacturing",
  "Biotechnology Manufacturing",
  "Renewable Energy Equipment",
  "Plastics and Rubber Products",
  "Metallurgy and Metal Fabrication",

  // Construction
  "Residential Construction",
  "Commercial Construction",
  "Infrastructure Development",
  "Civil Engineering",
  "Heavy Construction",
  "Specialized Construction Services",
  "Green Building and Sustainable Construction",
  "Demolition and Site Preparation",

  // Financial Services
  "Banking",
  "Insurance",
  "Investment and Asset Management",
  "Stock Market and Securities",
  "Fintech",
  "Venture Capital",
  "Microfinance",
  "Real Estate Finance",

  // Technology and Digital Services
  "Software Development",
  "Cloud Computing",
  "Cybersecurity",
  "Artificial Intelligence and Machine Learning",
  "Data Analytics",
  "Web Development",
  "IT Consulting",
  "Network Infrastructure",

  // Healthcare
  "Healthcare Services",
  "Medical Devices",
  "Biotechnology",
  "Pharmaceutical Research",
  "Telemedicine",
  "Medical Equipment",

  // Education
  "K-12 Education",
  "Higher Education",
  "Online Learning",
  "Professional Training",
  "Educational Technology",

  // Media and Entertainment
  "Film and Television",
  "Music Production",
  "Gaming",
  "Streaming Services",
  "Digital Media",
  "Publishing",

  // Transportation and Logistics
  "Shipping",
  "Air Transportation",
  "Rail Transportation",
  "Trucking",
  "Warehousing",
  "Supply Chain Management",

  // Hospitality and Tourism
  "Hotels",
  "Restaurants",
  "Travel Agencies",
  "Event Management",
  "Tourism Services",

  // Retail
  "E-commerce",
  "Brick-and-Mortar Retail",
  "Wholesale",
  "Specialty Retail",
  "Department Stores",

  // Energy
  "Renewable Energy",
  "Fossil Fuels",
  "Nuclear Energy",
  "Solar Power",
  "Wind Energy",
  "Hydroelectric Power",

  // Telecommunications
  "Mobile Communications",
  "Internet Service Providers",
  "Satellite Communications",
  "Network Equipment",

  // Agriculture and Food
  "Crop Farming",
  "Organic Farming",
  "Food Distribution",
  "Agricultural Technology",
  "Sustainable Agriculture",
];

export function getCitiesForStates(states: string[]): string[] {
  const cities = new Set<string>();
  states.forEach((state) => {
    Object.keys(LOCATIONS[state] || {}).forEach((city) => cities.add(city));
  });
  return Array.from(cities);
}

export function getLocationsForCities(cities: string[]): string[] {
  const locations = new Set<string>();
  Object.values(LOCATIONS).forEach((stateData) => {
    Object.entries(stateData).forEach(([city, cityLocations]) => {
      if (cities.includes(city)) {
        (cityLocations as string[]).forEach((location) =>
          locations.add(location)
        );
      }
    });
  });
  return Array.from(locations);
}